table Tabuľka
	lineageTag: 560ecd61-c499-41e4-bcfa-00500b86b980

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 9dba854c-a1d3-4828-b57f-0de0ddbd018b
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Hondnota
		dataType: string
		lineageTag: 50b7396b-9ba6-4505-8afe-a4dc567c522c
		summarizeBy: none
		sourceColumn: Hondnota

		annotation SummarizationSetBy = Automatic

	partition Tabuľka = m
		mode: import
		source =
				let
				  Zdroj = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUSooKqtUitWJVjICclKKSjMgPGMgr6QotSRTKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Hondnota = _t]),
				  #"Zmenený typ stĺpca" = Table.TransformColumnTypes(Zdroj, {{"ID", Int64.Type}, {"Hondnota", type text}}, "sk")
				in
				  #"Zmenený typ stĺpca"

	annotation PBI_ResultType = Table

